source:
  - '%id%'
  - '%id%.yml'
dest: '%id%'
actions:
  field.storage.node.field_related_content:
    value: {  }
  field.storage.node.field_my_text:
    value: {  }
  field.storage.node.field_my_date:
    value: {  }
  node.type.project_blog:
    value: { }
  field.field.node.project_blog.field_related_content:
    value: {  }
  field.field.node.project_blog.field_my_text:
    value: {  }
  field.field.node.project_blog.field_my_date:
    value: {  }
  field.storage.node.field_my_list:
    value: {  }
  field.field.node.project_blog.field_my_list:
    value: {  }
  field.storage.node.field_components:
    value: {  }
  field.field.node.project_blog.field_components:
    value: {  }
  field.field.node.project_blog.body:
    value: {  }
  core.entity_form_display.node.project_blog.default:
    value: {  }
  core.entity_view_display.node.project_blog.default:
    value: {  }
