services:
  config_override.override_site:
    class: \Drupal\config_override\SiteConfigOverrides
    arguments: ['@app.root', '@cache.data']
    tags:
      - { name: config.factory.override }
  config_override.override_modules:
    class: \Drupal\config_override\ModuleConfigOverrides
    arguments: ['@app.root', '@module_handler', '@cache.data']
    tags:
      - { name: config.factory.override }
