# Docker and Docker Compose based environment for Drupal.
version: '2.1'

# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

services:
  # Main Application service.
  www:
    container_name: d8test_www
    image: phase2/apache-php:php70
    network_mode: "bridge"
    environment:
      DOCROOT: /var/www/docroot
      PHP_MAX_EXECUTION_TIME: 60
      PHP_XDEBUG: "true"
      PHP_XHPROF: "true"
    links:
      - db
      - cache
    volumes:
      - .:/var/www # will be mounted on /var/www
    labels:
      com.dnsdock.name: www
      com.dnsdock.image: d8test

  # Memcached node
  cache:
    container_name: d8test_cache
    image: phase2/memcache
    environment:
      # Memcached memory limit in megabytes
      # MEMCACHED_MEMORY_LIMIT: 512
      MEMCACHE_MAX_MEMORY: 512
    network_mode: "bridge"
    labels:
      com.dnsdock.name: cache
      com.dnsdock.image: d8test

  # DB node
  db:
    container_name: d8test_db
    image: phase2/mariadb
    environment:
      MYSQL_USER: drupal
      MYSQL_PASS: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - /data/d8test_local:/var/lib/mysql
    network_mode: "bridge"
    labels:
      com.dnsdock.name: db
      com.dnsdock.image: d8test
