name: 'Config Templates'
type: module
core: 8.x
dependencies:
  - config_actions
  - datetime
  - entity_reference_revisions
  - field
  - file
  - image
  - language
  - menu_ui
  - node
  - options
  - paragraphs
  - path
  - taxonomy
  - text
  - user
