# This is an action used to create a content type
# Intended to be called via the "include" plugin from other actions

# Provide your own replacement variables in the calling Action
"%name%": "Vocab Name"
"%vocab%": "vocab_id"

# Prevent enabling this module from running this action automatically
auto: false

actions:

  vocabulary:
    source: [ "%dest%", "taxonomy.vocabulary.yml" ]
    dest: "taxonomy.vocabulary.%vocab%"
