plugin: include
module: config_templates

"%bundle%": "project_blog"

actions:

  content_type:
    file: "content_type"
    value:
      name: "My Project Blog"
      description: "This is the blog content type for the project"

  fields:
    file: "field"
    key: "%name%.%type%"

    actions:

      body.body:
        value:
          label: "Blog Description UPDATED"
          description: "This is the description field for the blog"

      field_my_text.text:
        value:
          label: "A Text New Value"

      field_my_date.date:
        value:
          label: "A Date Value"
          description: "This is a simple date field allowing 2 values"
          cardinality: 2

      field_my_list.list:
        value:
          label: "A Selection List"
          description: "Select a value from this list"
          settings:
            allowed_values:
              -
                value: 'Item 1'
                label: 'Item 1'
              -
                value: 'Item 2'
                label: 'Item 2'

      field_related_content.content_ref:
        value:
          label: "Related blogs"
          description: "Select a related blog article"
          settings:
            handler_settings:
              target_bundles:
                - page
                - project_blog

      field_components.paragraph:
        value:
          label: "Component List"
          description: "Select components to add to the blog"
          settings:
            target_type: paragraph
            handler_settings:
              target_bundles_drag_drop:
                p2component_text:
                  enabled: true
                p2component_image:
                  enabled: true

# You can even override values later if you want to keep track of history
# Or just make some minor tweaks/overrides to existing configs.
  overrides:
    plugin: change
    source: "%id%"

    actions:

      field.field.node.project_blog.body:
        value:
          description: "This is updated help text"
